### ISSUE TITLE
Add phpunit tests

### ISSUE THREAD

**Issue by mikkeschiren** [digitalist-se/extratools#1]
To get this plugin to a stable release - we need to have test coverage with phpunit tests.

**Comment by mikkeschiren** [comment]
First goal: Test coverage 70% (beta release)
Second goal: 100% (stable)

**Comment by madmath03** [comment]
Testing it in a "complete" Matomo instance with Travis-CI plus docker might also be useful.

**Comment by jorgeuos** [comment]
I'm gonna look into this, this week hopefully.

**Comment by mikkeschiren** [comment]
This is now started (5.x branch), so closing this issue
