### ISSUE TITLE
site:update  command

### ISSUE THREAD

**Issue by chriscroome** [digitalist-se/extratools#12]
If the list of URL's needs to be added to for a site, eg add `www.example.org` to the `site_url` table for the `www.example.com` site, there isn't currently a way to do this using the ExtraTools command line interface.

**Comment by mikkeschiren** [comment]
I have been on a looong vacation, but ill start look into issues very soon.

**Comment by mikkeschiren** [comment]
Long time... but now there  is a site:url command to add more urls to an existing site.

**Comment by chriscroome** [comment]
Nice one @mikkeschiren I shall look at updating my Ansible code to make use of this when I have some time also.
