### ISSUE TITLE
Install issue with davaxi/sparkline

### ISSUE THREAD

**Issue by chriscroome** [digitalist-se/extratools#15]
I can't see to get past this issue when using Composer to install ExtraTools:

> The .git directory is missing from `vendor/davaxi/sparkline`, see https://getcomposer.org/commit-deps for more information 

Any suggestions?

**Comment by chriscroome** [comment]
It appears that [this branch for sparkline](https://github.com/matomo-org/Sparkline/tree/multiple-series) is the one that is needed?

**Comment by mikkeschiren** [comment]
will look into this

**Comment by chriscroome** [comment]
I think the problem is that `composer require symfony/yaml:~2.6.0` removes the `davaxi/sparkline` version shipped with Matomo?

```
composer require symfony/yaml:~2.6.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 1 removal
  - Removing davaxi/sparkline (dev-multiple-series)
  - Installing symfony/yaml (v2.6.13): Loading from cache
  - Installing symfony/process (v3.4.32): Loading from cache
Package piwik/cache is abandoned, you should avoid using it. Use matomo/cache instead.
Package piwik/decompress is abandoned, you should avoid using it. Use matomo/decompress instead.
Package piwik/ini is abandoned, you should avoid using it. Use matomo/ini instead.
Generating autoload files
```

**Comment by mikkeschiren** [comment]
I think the major problem here is there is breaking changes in 3.12.0 - but this fixes the problem for me (automatic build pipeline):
```
curl https://raw.githubusercontent.com/matomo-org/matomo/3.x-dev/composer.json -o /var/www/html/composer.json
rm -rf /var/www/html/vendor/davaxi/sparkline
composer require symfony/process:^3.4 && composer require symfony/yaml:~2.6.0 && composer require davaxi/sparkline:^1.1
```

**Comment by chriscroome** [comment]
Cheers @mikkeschiren I was reaching the same conclusion, I suspect that this work around might have some side effects due to not using [this version of sparkline](https://github.com/matomo-org/Sparkline/tree/multiple-series) but I haven't looked into that&hellip;

**Comment by mikkeschiren** [comment]
Hm - I got one problem - "Too few arguments to function Davaxi\Sparkline::setData"

**Comment by chriscroome** [comment]
Would it help if the Matomo developer forked Sparkline and then that version could be used rather than the un-maintained version?

**Comment by mikkeschiren** [comment]
Hm, I missed that they specified the repo in composer.json. Testing to checkout the correct branch :-)

**Comment by mikkeschiren** [comment]
Updated my fix above ^

**Comment by chriscroome** [comment]
Thanks @mikkeschiren, so the problem was caused by [composer.json being omitted from the latest version](https://github.com/matomo-org/matomo-package/pull/103/files) and since the repo for Sparkline had been changed this wasn't picked up for Matomo sites that were being upgraded and this caused the original error I reported at the top of this thread.

Do the [install instructions](https://github.com/digitalist-se/extratools#in-composerjson-matomo-root) need updating to include downloading the correct version of `composer.json`, something like the following before using `./console matomo:install`?

```bash
export MATOMO_VERSION="3.12.0"
wget https://builds.piwik.org/signature.asc -O matomo.asc
gpg --import matomo.asc
wget https://builds.matomo.org/matomo-${MATOMO_VERSION}.tar.gz
wget https://builds.matomo.org/matomo-${MATOMO_VERSION}.tar.gz.asc
gpg --verify matomo-${MATOMO_VERSION}.tar.gz.asc
tar -zxvf matomo-${MATOMO_VERSION}.tar.gz
cd matomo
wget https://github.com/matomo-org/matomo/raw/${MATOMO_VERSION}/composer.json -O composer.json
composer require symfony/yaml:~2.6.0
composer require symfony/process:^3.4
```
FWIW I'm [using Ansible](https://git.coop/webarch/matomo/blob/master/tasks/install.yml) for this.
