### ISSUE TITLE
feat: Use same DB variables as official docker image

### ISSUE THREAD

**Issue by madmath03** [digitalist-se/extratools#16]
Hi,

It might be nice to use the same database environment variables as the [official docker](https://github.com/matomo-org/docker#matomo-installation):
```
MATOMO_DATABASE_HOST
MATOMO_DATABASE_ADAPTER
MATOMO_DATABASE_TABLES_PREFIX
MATOMO_DATABASE_USERNAME
MATOMO_DATABASE_PASSWORD
MATOMO_DATABASE_DBNAME
```

**Comment by mikkeschiren** [comment]
Yes, totally agree - will look into this - have not have the time I wanted to work on the plugin lately, but hopefully will have very soon.

**Comment by mikkeschiren** [comment]
This is now added in 0.1.0-beta7. Thanks for reporting this @madmath03 !

**Comment by chriscroome** [comment]
Thanks for also keeping the old env vars for backwards compatibility. :+1:
