### ISSUE TITLE
Incompatibility With 3.13.4 Zip Distribution

### ISSUE THREAD

**Issue by rfpludwick** [digitalist-se/extratools#19]
Following the installation instructions, Matomo's `console` breaks after running the two `composer` commands:

```
composer require symfony/yaml:~2.6.0
composer require symfony/process:^3.4
```

Error upon `console` invocation:

```
$ ./console
PHP Fatal error:  Uncaught Error: Class 'Piwik\Plugin\Manager' not found in <dir>/core/bootstrap.php:46
```

**Comment by mikkeschiren** [comment]
Hi, sorry for not have seen this, you should be able to follow this to solve the issue:
https://github.com/digitalist-se/extratools/issues/18#issuecomment-606250135
