### ISSUE TITLE
Installing ExtraTools inside Matomo Docker container

### ISSUE THREAD

**Issue by martinraie** [digitalist-se/extratools#22]
I'm using Matomo as Docker container and I'm trying to use ExtraTools to automate the installation. As I understand ExtraTools depends on symfony/yaml and symfony/process and composer is needed to install them. But there doesn't seem to be composer inside official Matomo Docker image. What is the best approach of using ExtraTools inside Docker container? Currently I'm starting to feel that I would need another tool which would automate installation of ExtraTools 😀.

**Comment by chriscroome** [comment]
I automated the install for Matomo 3.x using Ansible, but [this doesn't work with 4.x](https://github.com/digitalist-se/extratools/issues/21), first [download the corresponding `composer.json`](https://git.coop/webarch/matomo/-/blob/ab5857dc70a70319165e7c1de5a5db1fd81b9e21/tasks/download.yml#L52) and then [remove `davaxi/sparkline`](https://git.coop/webarch/matomo/-/blob/ab5857dc70a70319165e7c1de5a5db1fd81b9e21/tasks/extratools.yml#L2) and then [run `composer require`](https://git.coop/webarch/matomo/-/blob/ab5857dc70a70319165e7c1de5a5db1fd81b9e21/tasks/extratools.yml#L11) and then download the plugin and activate it, I can't see why this couldn't all all be written in Bash for a Docker file.

**Comment by martinraie** [comment]
Thanks for the reply. Yes, it's doable this way but it requires some extra work. I have to create my own Dockerfile, install composer and do all those steps which you mention. I'm not too familiar with the PHP ecosystem and was hoping I could use the official image without much hassle. I guess I'll stick to manual install without using ExtraTools.
