### ISSUE TITLE
Database is not correctly populated - matomo_site table is empty

### ISSUE THREAD

**Issue by esedeka** [digitalist-se/extratools#25]
Hi,

I'm deploying matomo 3.14.1 in a kubernetes cluster using your Helm charts https://github.com/digitalist-se/matomo-kubernetes and I got everything running but when I login into matomo it says:

Error: no website was found in this Matomo installation.
Check the table 'matomo_site' in your database, it should contain your Matomo websites.

I have checked DB and table is empty indeed. 

Installation is using ExtraTools-3.1.0-beta16 downloaded from matomo plugin marketplace for matomo 3.x

I have manually executed ./console matomo:install --install-file=/tmp/matomo/install.json --force --do-not-drop-db 

with 
---- install.json ---
{
  "PluginsInstalled": [
    "Diagnostics",
    "DBStats",
    "Login",
    "CoreAdminHome",
    "UsersManager",
    "SitesManager",
    "Installation",
    "Monolog",
    "Intl",
    "CorePluginsAdmin",
    "CoreHome",
    "WebsiteMeasurable",
    "CoreVisualizations",
    "Proxy",
    "API",
    "Transitions",
    "Actions",
    "Referrers",
    "UserLanguage",
    "DevicesDetection",
    "Goals",
    "SEO",
    "Events",
    "UserCountry",
    "GeoIp2",
    "VisitsSummary",
    "VisitFrequency",
    "VisitTime",
    "VisitorInterest",
    "CoreUpdater",
    "CoreConsole",
    "UserCountryMap",
    "Live",
    "ImageGraph",
    "Annotations",
    "Insights",
    "Morpheus",
    "Contents",
    "DevicePlugins",
    "UserId",
    "ExtraTools",
    "LanguagesManager",
    "SegmentEditor",
    "Dashboard",
    "ScheduledReports",
    "PrivacyManager",
    "CustomVariables",
    "IntranetMeasurable",
    "Widgetize",
    "MultiSites",
    "Ecommerce",
    "RssWidget",
    "Feedback",
    "TwoFactorAuth",
    "MobileMessaging",
    "Overlay",
    "BulkTracking",
    "Resolution",
    "Heartbeat",
    "Marketplace",
    "ProfessionalServices",
    "UserConsole"
  ],
    "User": {
        "username": "foo",
        "pass": "mypass",
        "email": "bar@foo.bar"
    },
  "Site": {
    "name": "localhost",
    "url": "http://localhost"
  },
  "Config": {
    "log": {
      "log_level": "DEBUG"
    },
    "General": {
      "show_update_notification_to_superusers_only": 1,
      "noreply_email_address": "noreply@digitalistgroup.com",
      "enable_framed_pages": 1,
      "enable_framed_settings": 1,
      "enable_trusted_host_check": 0,
      "enable_plugin_update_communication": 0,
      "enable_auto_update": 0,
      "enable_installer": 0,
      "enable_internet_features": 0,
      "enable_plugins_admin": 0,
      "enable_plugin_upload": 0,
      "enable_geolocation_admin": 1,
      "proxy_client_headers[]": "HTTP_X_FORWARDED_FOR",
      "browser_archiving_disabled_enforce": 1,
      "enable_browser_archiving_triggering": 0,
      "archiving_range_force_on_browser_request": 0,
      "enable_sql_optimize_queries": 0,
      "enabled_periods_UI": "day,week,month,year,range",
      "enabled_periods_API": "day,week,month,year,range",
      "session_save_handler": "dbtable",
      "enable_marketplace": 0,
      "enable_general_settings_admin": 1,
      "piwik_pro_ads_enabled": 0,
      "assume_secure_protocol": 1,
      "cors_domains[]": "*",
      "datatable_archiving_maximum_rows_referrers": 2000,
      "datatable_archiving_maximum_rows_subtable_referrers": 2000,
      "datatable_archiving_maximum_rows_actions": 2000,
      "datatable_archiving_maximum_rows_subtable_actions": 2000,
      "datatable_archiving_maximum_rows_events": 2000,
      "datatable_archiving_maximum_rows_subtable_events": 2000,
      "datatable_archiving_maximum_rows_custom_variables": 2000,
      "datatable_archiving_maximum_rows_subtable_custom_variables": 2000,
      "time_before_today_archive_considered_outdated": 2700,
      "time_before_week_archive_considered_outdated": 10800,
      "time_before_month_archive_considered_outdated": 32400,
      "time_before_year_archive_considered_outdated": 64800,
      "time_before_range_archive_considered_outdated": 10800
    }
  }
}
--- eof install.json ---

and no error so far, console says:

Installing Matomo
Starting install
Deleting cache
Initialising Database Connections
Create Matomo core tables
Updating Components
Creating Super user
Activated Diagnostics
Activated DBStats
Activated Login
Activated CoreAdminHome
Activated UsersManager
Activated SitesManager
Activated Installation
Activated Monolog
Activated Intl
Activated CorePluginsAdmin
Activated CoreHome
Activated WebsiteMeasurable
Activated CoreVisualizations
Activated Proxy
Activated API
Activated Transitions
Activated Actions
Activated Referrers
Activated UserLanguage
Activated DevicesDetection
Activated Goals
Activated SEO
Activated Events
Activated UserCountry
Activated GeoIp2
Activated VisitsSummary
Activated VisitFrequency
Activated VisitTime
Activated VisitorInterest
Activated CoreUpdater
Activated CoreConsole
Activated UserCountryMap
Activated Live
Activated ImageGraph
Activated Annotations
Activated Insights
Activated Morpheus
Activated Contents
Activated DevicePlugins
Activated UserId
Activated ExtraTools
Activated LanguagesManager
Activated SegmentEditor
Activated Dashboard
Activated ScheduledReports
Activated PrivacyManager
Activated CustomVariables
Activated IntranetMeasurable
Activated Widgetize
Activated MultiSites
Activated Ecommerce
Activated RssWidget
Activated Feedback
Activated TwoFactorAuth
Activated MobileMessaging
Activated Overlay
Activated BulkTracking
Activated Resolution
Activated Heartbeat
Activated Marketplace
Activated ProfessionalServices
Activated UserConsole
Finalising...
We are done! Welcome to Matomo!
Now you can login with user foo and password mypass

matomo_user table is populated with that user but It's like it is not writting everything required to DB, but it seems that there is no error.

Any clue?

Thank you very much indeed!!!

**Comment by esedeka** [comment]
Well I think it works executing:


./console site:add  --name=Foo --urls=https//foo.bar 

But it's strange it doesn't works from install.json

**Comment by jorgeuos** [comment]
Weird, I'm running it now 

Could be related to `"assume_secure_protocol": 1,` and you're setting `http`
```
"Site": {
"name": "localhost",
"url": "http://localhost"
},
```

Check this Matomo issue for more details: https://github.com/matomo-org/matomo/issues/13374
