### ISSUE TITLE
Uncaught exception: Error: Class "Symfony\Component\Process\Process" not found in /var/www/matomo/plugins/ExtraTools/Lib/Backup.php:36

### ISSUE THREAD

**Issue by ransome1** [digitalist-se/extratools#27]
Hey guys.

Great work on these helpful little tools.  I downloaded the 4.0.0-beta5 release from the Matomo marketplace.

IBut  can't get the database backup to work.

```
$ sudo /usr/bin/php /var/www/matomo/console database:backup
Starting backup job:
ERROR [2022-01-14 21:27:31] 243955  Uncaught exception: Error: Class "Symfony\Component\Process\Process" not found in /var/www/matomo/plugins/ExtraTools/Lib/Backup.php:36
Stack trace:
#0 /var/www/matomo/plugins/ExtraTools/Commands/BackupDb.php(99): Piwik\Plugins\ExtraTools\Lib\Backup->execute()
#1 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\ExtraTools\Commands\BackupDb->execute()
#2 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run()
#3 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand()
#4 [internal function]: Symfony\Component\Console\Application->doRun()
#5 /var/www/matomo/core/Console.php(130): call_user_func()
#6 /var/www/matomo/core/Access.php(670): Piwik\Console->Piwik\{closure}()
#7 /var/www/matomo/core/Console.php(131): Piwik\Access::doAsSuperUser()
#8 /var/www/matomo/core/Console.php(82): Piwik\Console->doRunImpl()
#9 /var/www/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
#10 /var/www/matomo/console(32): Symfony\Component\Console\Application->run()
#11 {main}
Uncaught exception in /var/www/matomo/plugins/ExtraTools/Lib/Backup.php line 36:
Class "Symfony\Component\Process\Process" not found
```

Do you have an idea what might be going wrong here?

**Comment by jorgeuos** [comment]
Looks like a bug. I will check this today since I'm currently working on some enhancements.

**Comment by mikkeschiren** [comment]
Thank you for the bug report  @ransome1!! 
Have you installed the required dependencies? See: https://github.com/digitalist-se/extratools#dependencies

**Comment by jorgeuos** [comment]
Yeah, didn't think about that, I thought Process was already added. But that would explain this behaviour.

Otherwise I did some refactoring that might be useful or at least improve readability.

[4.x-dev-fixes](https://github.com/digitalist-se/extratools/tree/4.x-dev-fixes)

**Comment by everflux** [comment]
I have the same issue, testing 4.x-dev-fixes yields the same result.
My use case is a little bit different, though - I would like to use the regular matomo docker image as foundation for the setup.
As a workaround I added "--do-not-drop-db" which helped a little - but no initial site is created and the matomo installation is broken afterwards.

**Comment by ransome1** [comment]
@mikkeschiren  @jorgeuos sorry for my late reply!

I installed both dependencies and it didn't clear up the error.

As for the composer.json I'm a bit confused. This file doesn't exist in my Matomo root. I created it with the contents mentioned above but I didn't solve the problem.

**Comment by mikkeschiren** [comment]
There are some minor issues in the latest releases, including not getting the first site setup, I am looking into this. For the composer.json I will add some more documentation to try to help out.

**Comment by mikkeschiren** [comment]
I am closing this, if you don't have the composer.json or composer.lock in you Matomo root, you need to download these from the matom repo.
